name: Publish

on:
  release:
  types: [created]

jobs: 
  build-and-publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build
        run: bun run build

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        

